"""add_website_url_to_cards

Revision ID: 65fbceb20041
Revises: 9a1a50355ffd
Create Date: 2026-04-01 12:24:46.913659

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "65fbceb20041"
down_revision: Union[str, Sequence[str], None] = "9a1a50355ffd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cards", sa.Column("vacancy_url", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "vacancy_url")
    # ### end Alembic commands ###
