"""rename cards to applications

Revision ID: f688a8173bee
Revises: 65fbceb20041
Create Date: 2026-04-01 13:09:04.735475

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f688a8173bee"
down_revision: Union[str, Sequence[str], None] = "65fbceb20041"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "HR_INTERVIEW",
                "TECH_INTERVIEW",
                "DIRECTOR_INTERVIEW",
                "OFFER",
                "REJECTED",
                "ARCHIVED",
                name="applicationstatus",
            ),
            nullable=False,
        ),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("contacts", sa.String(length=500), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("vacancy_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("cards")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cards",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "CREATED",
                "HR_INTERVIEW",
                "TECH_INTERVIEW",
                "DIRECTOR_INTERVIEW",
                "OFFER",
                "REJECTED",
                "ARCHIVED",
                name="cardstatus",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("company_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("contacts", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("comments", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("vacancy_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("cards_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("cards_pkey")),
    )
    op.drop_table("applications")
    # ### end Alembic commands ###
